### PR TITLE
multiple bad-merge fixes

### PR DESCRIPTION
**Pull request by sezero**
I broke down commits into smallest possible individual commits.

I haven't touched SDL_os2.[ch] and SDL.c changes: mainstream handles
it differently using `defined(HAVE_ICONV) && defined(HAVE_ICONV_H)`
checks - should be handled when you guys migrate to version 2.0.20
(which should be released tomorrow or something.)

### CODE REVIEW

**Review by SilvanScherrer — APPROVED** [review]

**Review by SilvanScherrer — APPROVED** [review]

**Review by SilvanScherrer — APPROVED** [review]

**Comment by SilvanScherrer** [comment]
I commited most but not all. Need to check them first

**Comment by sezero** [comment]
OK, feel free to ask me about the others not yet applied.

BTW, SDL 2.0.20 is already released, so you can upgrade to it:
https://github.com/libsdl-org/SDL/releases/tag/release-2.0.20

If you do upgrade to it, I suggest that you cherry-pick these
three post-release commits:
https://github.com/libsdl-org/SDL/commit/b2656776109a71f84d43256533d045a51bffa8b5
https://github.com/libsdl-org/SDL/commit/c6c4d4211b10f57e902c6ed8d054f0dcbe44eded
https://github.com/libsdl-org/SDL/commit/7527c8d3d78a09620efab3634cd2aa9f67a29a49

**Comment by josch1710** [comment]
@sezero : Do you know, why the HIDAPI driver seems to only supports game controllers?
Do I have to implement  platofrm specific code to support generic joysticks via USB?

**Comment by sezero** [comment]
> @sezero : Do you know, why the HIDAPI driver seems to only supports game controllers?

AFAIK, the purpose of addition of HIDAPI to SDL was only supporting game controllers
in a cross-platform way in Steam. Although SDL _might_ (or might not) use hidapi for
other purposes after 2.0.18/20 where it was promoted to be one of core SDL susbystems.

> Do I have to implement platofrm specific code to support generic joysticks via USB?

I _guess_ so, although Sam may have better answer for it.

**Comment by sezero** [comment]
> @sezero : Do you know, why the HIDAPI driver seems to only supports game controllers?

AFAIK, the purpose of addition of HIDAPI to SDL was only supporting game controllers
in a cross-platform way in Steam. Although SDL _might_ (or might not) use hidapi for
other purposes after 2.0.18/20 where it was promoted to be one of core SDL susbystems.

> Do I have to implement platofrm specific code to support generic joysticks via USB?

I _guess_ so, although Sam (@slouken) may have better answer for it.

**Comment by SilvanScherrer** [comment]
most is done. some changes are not applied right now. while doing 2.0.20 we recheck them.

**Comment by sezero** [comment]
OK, great.

Question: In mainstream, we use OpenWatcom in Github Actions for OS/2.
Is it possible to use a klibc / emx based cross-toolchain (maybe some
docker image?) too, so I don't have to work blindly for gcc/autotools/
cmake for os/2?

(I know it's possibly not available, but asking anyway..)

**Comment by SilvanScherrer** [comment]
I heavily doubt we have something for that. Might be others know more.

**Comment by josch1710** [comment]
> I _guess_ so, although Sam (@slouken) may have better answer for it.
Where would be the best place to contact him? On the SDL forum?

**Comment by SilvanScherrer** [comment]
Please do me a favour. Dont abuse pull request comments for a conversation which is out of the scope of the pull request.

**Comment by josch1710** [comment]
Sure. Can we get Sezero into the slack?

**Comment by SilvanScherrer** [comment]
@sezero could you send me you Mail address eventually?
Info@bitwiseworks.com

**Comment by sezero** [comment]
> @sezero could you send me you Mail address eventually? [Info@bitwiseworks.com](mailto:Info@bitwiseworks.com)

Sent email to you at that address

**Comment by sezero** [comment]
>> `I _guess_ so, although Sam (@slouken) may have better answer for it.`
>
> @sezero: Where would be the best place to contact him? On the SDL forum?

Either the SDL forum at https://discourse.libsdl.org/ or at the github
issues https://github.com/libsdl-org/SDL/issues

**Comment by sezero** [comment]
@SilvanScherrer: you may want to cherry-pick https://github.com/libsdl-org/SDL/commit/dfbe1f7248649fdca86368bc51f3592931c8ebe5 from mainstream for fixes to SDL_GetBasePath()

**Pull request closed without merging**
